---
kind: Service
apiVersion: v1
metadata:
  name: spark-eventsnotification
  labels:
    app: spark-eventsnotification
    Platform: spark
  namespace: spark
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: spark-eventsnotification
  type: NodePort
