apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-ui
  labels:
    app: spark-ui
    Platform: spark
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-ui
  template:
    metadata:
      labels:
        app: spark-ui
    spec:
      serviceAccountName: spark
      containers:
      - name: spark-ui
        image: manu207/spark-ui:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: "/"
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: "/"
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 4Gi
        env:
        - name: project_env
          value: prod
        - name: project_name
          value: spark-ui
      imagePullSecrets:
      - name: docker-secrets
