---
kind: Service
apiVersion: v1
metadata:
  name: spark-websocket
  labels:
    app: spark-websocket
    Platform: spark
  namespace: spark
spec:
  ports:
  - port: 80  
    targetPort: 3000  
  selector:
    app: spark-websocket
  type: NodePort
