---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snoops-data-ingestion
  labels:
    app: snoops-data-ingestion
    Platform: snoops
  namespace: snoops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snoops-data-ingestion
  template:
    metadata:
      labels:
        app: snoops-data-ingestion
    spec:
      serviceAccountName: snoops
      containers:
      - name: snoops-data-ingestion
        image: 424258464218.dkr.ecr.us-east-1.amazonaws.com/snoops-data-ingestion:latest
        ports:
        - containerPort: 8000
        # livenessProbe:
        #   httpGet:
        #     path: "/authentication"
        #     port: 8000
        #     scheme: HTTP
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 10
        #   periodSeconds: 30
        #   successThreshold: 1
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: "/authentication"
        #     port: 8000
        #     scheme: HTTP
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 10
        #   periodSeconds: 30
        #   successThreshold: 1
        #   failureThreshold: 3
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 4Gi
        env:
        - name: project_env
          value: development
        - name: project_name
          value: snoops-data-ingestion