---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snoops-ui
  labels:
    app: snoops-ui
    Platform: snoops
  namespace: snoops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snoops-ui
  template:
    metadata:
      labels:
        app: snoops-ui
    spec:
      serviceAccountName: snoops
      containers:
      - name: snoops-ui
        image: 424258464218.dkr.ecr.us-east-1.amazonaws.com/snoops-ui:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: "/"
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 600
          timeoutSeconds: 10
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: "/"
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 600
          timeoutSeconds: 10
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 4Gi
        env:
        - name: project_env
          value: development
        - name: project_name
          value: snoops-ui