---
kind: Service
apiVersion: v1
metadata:
  name: snoops-ui
  labels:
    app: snoops-ui
    Platform: snoops
  namespace: snoops-dev
spec:
  ports:
  - port: 443
    targetPort: 3000
  selector:
    app: snoops-ui
  type: NodePort